module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since:
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji: "😊"
        subtitle: "Web Developer"
        avatar:
            enabled: true
            local: true
            src: img/hehe.jpg
        phone: "+123 456 789"
        email: "thanhcong77@gmail.com"
        birthdate: "Jul 07, 2003"

    article:
        headingAnchor: false
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus
        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:
        utterances:
            repo:
            issueTerm: pathname
            label:
        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:
        remark42:
            host:
            site:
            locale:
        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - nick
                - mail
            locale:
                admin: Admin
                placeholder:
        twikoo:
            envId:
            region:
            path:
            lang:
        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            strict:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition:
            lang:
        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:
        cusdis:
            host:
            id:

    widgets:
        homepage: []
        page: []

    opengraph:
        twitter:
            site: "@your_twitter_username"
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: light

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
    pagination:
        perPage: 10